'tbBuscador%3AidFormBuscarProceso=tbBuscador%3AidFormBuscarProceso
&tbBuscador%3AidFormBuscarProceso%3AhddNumeroRuc=
&tbBuscador%3AidFormBuscarProceso%3AnombreEntidad=
&tbBuscador%3AidFormBuscarProceso%3Aj_idt32_input=
&tbBuscador%3AidFormBuscarProceso%3Aj_idt32_focus=
&tbBuscador%3AidFormBuscarProceso%3Aj_idt41_input=
&tbBuscador%3AidFormBuscarProceso%3Aj_idt41_focus=
&tbBuscador%3AidFormBuscarProceso%3AnumeroSeleccion=
&tbBuscador%3AidFormBuscarProceso%3AdescripcionObjeto=
&tbBuscador%3AidFormBuscarProceso%3AanioConvocatoria_input=2023
&tbBuscador%3AidFormBuscarProceso%3AanioConvocatoria_focus=
&tbBuscador%3AidFormBuscarProceso%3Aj_idt67_input=3
&tbBuscador%3AidFormBuscarProceso%3Aj_idt67_focus=
&tbBuscador%3AidFormBuscarProceso%3AcodigoSnip=
&tbBuscador%3AidFormBuscarProceso%3ACUI=
&tbBuscador%3AidFormBuscarProceso%3AsiglasEntidad=
&tbBuscador%3AidFormBuscarProceso%3Aj_idt95_input=
&tbBuscador%3AidFormBuscarProceso%3Aj_idt95_focus=
&tbBuscador%3AidFormBuscarProceso%3Adepartamento_input=
&tbBuscador%3AidFormBuscarProceso%3Adepartamento_focus=
&tbBuscador%3AidFormBuscarProceso%3Aprovincia_input=
&tbBuscador%3AidFormBuscarProceso%3Aprovincia_focus=
&tbBuscador%3AidFormBuscarProceso%3Adistrito_input=
&tbBuscador%3AidFormBuscarProceso%3Adistrito_focus=
&tbBuscador%3AidFormBuscarProceso%3AnumeroConvocatoria=
&tbBuscador%3AidFormBuscarProceso%3Aj_idt122_input=
&tbBuscador%3AidFormBuscarProceso%3Aj_idt122_focus=
&tbBuscador%3AidFormBuscarProceso%3AdfechaInicio_input=' . urlencode($fecha_inicio) . '
&tbBuscador%3AidFormBuscarProceso%3AdfechaFin_input=' . urlencode($fecha_final) . '
&tbBuscador%3AidFormBuscarProceso%3Aj_idt85_collapsed=false
&tbBuscador%3AidFormBuscarProceso%3AcodigoCaptcha=
&tbBuscador%3AidFormBuscarProceso%3AtxtNombreEntidad=
&tbBuscador%3AidFormBuscarProceso%3AtxtRucEntidad=
&tbBuscador%3AidFormBuscarProceso%3Atxtsigla=
&javax.faces.ViewState=' . urldecode($view_state) . '
&nidSistema=3
&ptoRetorno=LOCAL
&tbBuscador%3AidFormBuscarProceso%3AdtProcesos%3A0%3Aj_idt229=tbBuscador%3AidFormBuscarProceso%3AdtProcesos%3A0%3Aj_idt229
&ntipo=1
&nidProceso=' . $proceso . '
&nidConvocatoria=' . $convocatoria;